server {
  listen 80;
  server_name chess.a13v.com;

  location / {
    proxy_pass http://localhost:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /assets/ {
    root /Users/melnik0v/wwork/chess/public;
    expires max;
    add_header Cache-Control public;
  }

  location /packs/ {
    root /Users/melnik0v/wwork/chess/public;
    expires max;
    add_header Cache-Control public;
  }

  # Optionally, add other static file locations if needed
  location ~* \.(jpg|jpeg|gif|png|css|js|ico|html)$ {
    root /Users/melnik0v/wwork/chess/public;
    expires max;
    add_header Cache-Control public;
  }
}


